### PR TITLE
[ISSUE-1] Fixed line ending for windows os

### LINKED ISSUE #1: [ISSUE-1] Fix line ending
There is an issue with the package to parse ignore files if accessed from a Windows machine.

The root cause of the issue is different line endings used by different OS
in Linux/MAC it is supposed to be LF
whereas in Windows it is supposed to be CRLF

### PR DESCRIPTION
**Pull request by neerajverma101**
Added a function to check line ending in the ignore files
Now, the code is able to judge and act accordingly

### CODE REVIEW

File: bin/getAuditFileNames.js [hunk 1]
```diff
@@ -19,10 +19,11 @@ async function getAuditFileNames() {
   try {
     ['./.gitignore', './.eslintignore'].forEach((ignorefile) => {
       const ignoreContent = fs.readFileSync(ignorefile, 'utf8');
-      const parsedIgnoredContent = ignoreContent.split('\n').filter((line) => !line.startsWith('#') && line.trim() !== '');
+      const parsedIgnoredContent = ignoreContent.split(getLineEnding(ignoreContent)).filter((line) => !line.startsWith('#') && line.trim() !== '');
       ignorePatterns = [...ignorePatterns, ...parsedIgnoredContent]
     })
-  } catch (err) { }
+  } catch (err) {
+  }
```
Comment (ice-rahul) [inline bin/getAuditFileNames.js]:
```suggestion
  } catch (err) { }
```

**Review by ice-rahul — APPROVED** [review]
LGTM
